name: generator_pm_streamlit
channels:
  - snowflake
dependencies:
  - streamlit
  - pandas=2.*
  - numpy
  - plotly
  - scikit-learn
  - matplotlib
  - altair
  - pyyaml
  - snowflake-snowpark-python
